const $=selector=>document.querySelector(selector);
let csrf="",agents=[],sessions=[],activeAgent="",activeSession="",activeRevision="",activeSource="",activeRun=null,retryAction=null,searchTimer=null,pendingKey=null,commandCatalog=null,commandIndex=-1;
const sourceNames={active:"活会话",reset:"归档",panel:"面板会话"};
const panelCommands=[
  {name:"model",usage:"/model [模型]",description:"查看或设置当前会话模型"},
  {name:"think",usage:"/think [级别]",description:"查看或设置思考级别"},
  {name:"reasoning",usage:"/reasoning [on|off|stream]",description:"查看或设置思考内容可见性"},
  {name:"new",usage:"/new [标题]",description:"新建并切换到面板会话"},
  {name:"commands",usage:"/commands",description:"查看 OpenClaw 命令目录"},
  {name:"help",usage:"/help",description:"查看面板支持的命令"},
  {name:"status",usage:"/status",description:"查看 OpenClaw 状态"},
  {name:"models",usage:"/models",description:"查看可用模型"}
].map(command=>({...command,supported:true}));
panelCommands.push(...[
  ["compact","压缩会话上下文"],["stop","停止当前运行"],["reset","重置 OpenClaw 会话"],["config","修改 OpenClaw 配置"],["restart","重启 OpenClaw"],["bash","执行 shell 命令"],["tools","查看运行时工具"],["usage","查看用量"]
].map(([name,description])=>({name,usage:`/${name}`,description,supported:false})));
const commandResults=new Map();
async function api(path,options={}){const response=await fetch(`/api/v1${path}`,{...options,headers:{"content-type":"application/json","x-csrf-token":csrf,...options.headers}});const value=await response.json();if(!response.ok)throw Object.assign(new Error(value.error?.message||"请求失败"),{status:response.status,code:value.error?.code});return value.data}
function clear(node){node.replaceChildren()}
function showError(error,retry){const bar=$("#error");$("#error-message").textContent=error instanceof Error?error.message:String(error);bar.hidden=false;retryAction=retry||null;$("#retry").hidden=!retryAction}
function hideError(){$("#error").hidden=true;retryAction=null}
let editorResolve=null,editorPreviousFocus=null,editorRequired=false;
function finishEditor(value){const resolve=editorResolve;editorResolve=null;if($("#editor-dialog").open)$("#editor-dialog").close();if(editorPreviousFocus instanceof HTMLElement)editorPreviousFocus.focus();editorPreviousFocus=null;resolve?.(value)}
function openEditor({title,help,label,value="",multiline=false,required=false,confirm="确认"}){if(editorResolve)finishEditor(null);const dialog=$("#editor-dialog"),input=$("#editor-input"),textarea=$("#editor-textarea"),control=multiline?textarea:input;editorPreviousFocus=document.activeElement;editorRequired=required;$("#editor-title").textContent=title;$("#editor-help").textContent=help;$("#editor-label").textContent=label;$("#editor-label").htmlFor=control.id;$("#editor-submit").textContent=confirm;$("#editor-error").textContent="";input.hidden=multiline;textarea.hidden=!multiline;input.value=multiline?"":value;textarea.value=multiline?value:"";dialog.showModal();queueMicrotask(()=>control.focus());return new Promise(resolve=>{editorResolve=resolve})}
$("#editor-form").addEventListener("submit",event=>{event.preventDefault();const control=$("#editor-textarea").hidden?$("#editor-input"):$("#editor-textarea"),value=control.value;if(editorRequired&&!value.trim()){$("#editor-error").textContent="内容不能为空";control.focus();return}finishEditor(value)});
$("#editor-cancel").onclick=()=>finishEditor(null);$("#editor-dialog").addEventListener("cancel",event=>{event.preventDefault();finishEditor(null)});$("#editor-dialog").addEventListener("click",event=>{if(event.target===$("#editor-dialog"))finishEditor(null)});
async function boot(){try{const me=await api("/auth/session");csrf=me.csrfToken;$("#login").hidden=true;$("#app").hidden=false;await load()}catch{}}
$("#login-form").addEventListener("submit",async event=>{event.preventDefault();const form=new FormData(event.currentTarget);try{const me=await api("/auth/login",{method:"POST",body:JSON.stringify(Object.fromEntries(form))});csrf=me.csrfToken;$("#login").hidden=true;$("#app").hidden=false;await load()}catch(error){$("#login-error").textContent=error.message}});
async function load(){try{agents=await api("/agents");if(!activeAgent&&agents.length)activeAgent=String(agents[0].id);sessions=activeAgent?await api(`/sessions?agentId=${encodeURIComponent(activeAgent)}`):[];renderAgents();renderSessions();hideError()}catch(error){showError(error,load)}}
function normalizeCommand(command){const raw=String(command?.name??command?.command??"").replace(/^\//,"").trim();if(!raw)return null;const local=panelCommands.find(item=>item.name===raw);return{...command,...local,name:raw,usage:String(command?.usage||local?.usage||`/${raw}`),description:String(command?.description||local?.description||"OpenClaw 命令"),supported:Boolean(local&&command?.supported!==false)}}
async function loadCommands(){commandCatalog=commandCatalog||panelCommands;return commandCatalog}
function commandQuery(value){const match=value.match(/^\/(\S*)$/);return match?match[1].toLowerCase():null}
function hideCommands(){const menu=$("#command-menu");menu.hidden=true;clear(menu);commandIndex=-1;$("#message").removeAttribute("aria-activedescendant")}
async function showCommands(){const textarea=$("#message"),query=commandQuery(textarea.value);if(query===null||activeSource!=="panel"){hideCommands();return}const commands=(await loadCommands()).filter(command=>command.name.toLowerCase().includes(query));const menu=$("#command-menu");clear(menu);if(!commands.length){hideCommands();return}for(const command of commands){const button=document.createElement("button");button.type="button";button.id=`command-${command.name.replace(/[^a-z0-9_-]/gi,"-")}`;button.setAttribute("role","option");button.dataset.command=command.name;button.disabled=!command.supported;const label=document.createElement("span"),help=document.createElement("small");label.textContent=command.usage;help.textContent=command.supported?command.description:"仅 OpenClaw 原生渠道可用";button.append(label,help);button.onmousedown=event=>event.preventDefault();button.onclick=()=>selectCommand(command);menu.append(button)}menu.hidden=false;commandIndex=-1}
function selectCommand(command){const textarea=$("#message");textarea.value=command.usage.includes("[")?`/${command.name} `:`/${command.name}`;hideCommands();textarea.focus()}
function moveCommandSelection(delta){const enabled=[...$("#command-menu").querySelectorAll("button:not(:disabled)")];if(!enabled.length)return;commandIndex=(commandIndex+delta+enabled.length)%enabled.length;for(const button of $("#command-menu").querySelectorAll("button"))button.setAttribute("aria-selected",String(button===enabled[commandIndex]));$("#message").setAttribute("aria-activedescendant",enabled[commandIndex].id);enabled[commandIndex].scrollIntoView({block:"nearest"})}
function renderAgents(){const root=$("#agents");clear(root);for(const agent of agents){const button=document.createElement("button");button.className=`agent${String(agent.id)===activeAgent?" active":""}`;button.dataset.id=String(agent.id);const badge=document.createElement("b");badge.textContent=String(agent.label||"?").slice(0,1);button.append(badge,document.createTextNode(String(agent.label||agent.id||"")));button.onclick=async()=>{activeAgent=String(agent.id);activeSession="";activeRevision="";$("#search").value="";await load();$("#app").className="shell show-sessions"};root.append(button)}}
function sourceTag(kind){const tag=document.createElement("span");tag.className=`tag ${kind||""}`;tag.textContent=sourceNames[kind]||String(kind||"");return tag}
function renderSessions(values=sessions){const root=$("#sessions");clear(root);if(!values.length){const empty=document.createElement("p");empty.className="list-empty";empty.textContent=$("#search").value?"没有搜索结果":"还没有会话";root.append(empty);return}for(const session of values){const button=document.createElement("button");button.className=`session${String(session.recordId)===activeSession?" active":""}`;const title=document.createElement("strong");title.textContent=String(session.title||"未命名会话");title.append(sourceTag(session.sourceKind||session.kind));const detail=document.createElement("p");detail.textContent=`${session.updatedAt?new Date(session.updatedAt).toLocaleString():""} · ${session.messageCount||0} 条`;button.append(title,detail);if(session.hits?.length){const hit=document.createElement("p");hit.className="hit";hit.textContent=String(session.hits[0].snippet||"");button.append(hit)}button.onclick=()=>openSession(String(session.recordId));root.append(button)}}
function contentBlocks(entry){const message=entry?.message;if(!message||typeof message!=="object")return[];const content=message.content;if(message.role==="toolResult"){const text=Array.isArray(content)?content.map(block=>typeof block==="string"?block:typeof block?.text==="string"?block.text:JSON.stringify(block,null,2)).join("\n"):typeof content==="string"?content:JSON.stringify(content??message.details??"",null,2);return[{type:"tool_result",name:String(message.toolName||""),callId:String(message.toolCallId||""),text,isError:Boolean(message.isError)}]}if(typeof content==="string")return[{type:"text",text:content}];if(!Array.isArray(content))return[];return content.map(block=>{if(typeof block==="string")return{type:"text",text:block};if(!block||typeof block!=="object")return{type:"unknown",text:String(block)};const type=String(block.type||"unknown");if(type==="text")return{type,text:String(block.text||"")};if(type==="thinking")return{type,text:String(block.text??block.thinking??"")};if(type==="tool_use"||type==="toolCall")return{type:"tool_use",name:String(block.name||""),callId:String(block.id||""),input:block.input??block.arguments};if(type==="tool_result"||type==="toolResult")return{type:"tool_result",name:String(block.name||""),callId:String(block.toolCallId??block.tool_use_id??""),text:typeof block.content==="string"?block.content:JSON.stringify(block.content??block.result??block,null,2),isError:Boolean(block.isError)};return{type,name:String(block.name||""),text:JSON.stringify(block,null,2)}})}
function activeBranch(entries){const byId=new Map(entries.flatMap(entry=>typeof entry?.id==="string"?[[entry.id,entry]]:[]));let current=[...entries].reverse().find(entry=>typeof entry?.id==="string"&&entry.message),ids=new Set();while(current&&typeof current.id==="string"&&!ids.has(current.id)){ids.add(current.id);current=typeof current.parentId==="string"?byId.get(current.parentId):null}return ids.size?entries.filter(entry=>typeof entry?.id==="string"&&ids.has(entry.id)):entries}
function normalizeConversation(value){if(!value)return null;if(Array.isArray(value.messages))return value;const entries=activeBranch(Array.isArray(value.document?.entries)?value.document.entries:[]),messages=[],calls=new Map();for(const entry of entries){const role=entry?.message?.role;if(role!=="user"&&role!=="assistant"&&role!=="tool"&&role!=="toolResult")continue;const blocks=contentBlocks(entry);if(role==="toolResult"){const unmatched=[];for(const result of blocks){const call=result.callId&&calls.get(result.callId);if(call)call.result=result;else unmatched.push(result)}if(!unmatched.length)continue;messages.push({id:String(entry.id||""),role:"assistant",blocks:unmatched,canFork:false,canEdit:false});continue}const hasTool=blocks.some(block=>block.type==="tool_use"),stopReason=entry.stopReason??entry?.message?.stopReason,message={id:String(entry.id||""),role:role==="user"?"user":"assistant",blocks,canFork:role==="user"||role==="assistant"&&!hasTool&&stopReason!=="toolUse"&&stopReason!=="tool_use",canEdit:role==="user"};messages.push(message);for(const block of blocks)if(block.type==="tool_use"&&block.callId)calls.set(block.callId,block)}return{...value,title:value.title||"未命名会话",messages}}
async function openSession(id){try{const conversation=normalizeConversation(await api(`/sessions/${encodeURIComponent(id)}`));if(!conversation)throw new Error("会话不存在或已经移动");activeSession=id;activeRevision=String(conversation.revision||"");activeSource=String(conversation.sourceKind||"panel");$("#title").textContent=String(conversation.title||"未命名会话");$("#subtitle").textContent=sourceNames[activeSource]||"会话";const writable=activeSource==="panel";$("#message").disabled=!writable;$("#send").disabled=!writable;$("#message").placeholder=writable?"继续这段会话…":"从某条消息 fork 后可在面板继续";$("#composer-hint").textContent=writable?"Enter 发送 · Shift+Enter 换行 · / 命令":"只读来源 · 从消息处 fork 后继续";renderMessages(conversation.messages||[],commandResults.get(id)||[]);renderSessions();$("#app").className="shell show-conversation";hideCommands();hideError()}catch(error){showError(error,()=>openSession(id))}}
const normalizeConversationMessages=normalizeConversation;
normalizeConversation=function(value){if(!value?.document?.entries)return normalizeConversationMessages(value);const systemIds=new Set(),entries=value.document.entries.map(entry=>{if(entry?.message?.role!=="system")return entry;systemIds.add(String(entry.id||""));return{...entry,stopReason:"panel_command",message:{...entry.message,role:"assistant"}}});const normalized=normalizeConversationMessages({...value,document:{...value.document,entries}});if(normalized?.messages)for(const message of normalized.messages)if(systemIds.has(String(message.id||""))){message.canFork=false;message.canEdit=false;message.blocks=[{type:"text",text:`系统 · ${message.blocks?.map(block=>block.text||"").join("\n")||"会话设置已更新"}`}]}return normalized}
function action(label,handler){const button=document.createElement("button");button.type="button";button.textContent=label;button.onclick=handler;return button}
function renderMessages(messages,results=[]){const root=$("#messages");clear(root);if(!messages.length&&!results.length){const empty=document.createElement("div");empty.className="empty";empty.textContent="发送第一条消息开始会话";root.append(empty);return}for(const message of messages){const article=document.createElement("article");article.className=`message ${message.role==="user"?"user":"assistant"}`;for(const block of Array.isArray(message.blocks)?message.blocks:[]){if(block.type==="text"){const paragraph=document.createElement("p");paragraph.textContent=String(block.text||"");article.append(paragraph)}else{const details=document.createElement("details");details.className="block";const summary=document.createElement("summary");summary.textContent=block.type==="thinking"?"思考过程":block.type==="tool_result"?"工具结果":`工具调用 · ${block.name||""}`;const pre=document.createElement("pre");pre.textContent=String(block.text||JSON.stringify(block.input,null,2)||"");details.append(summary,pre);if(block.type==="tool_use"&&block.result){const label=document.createElement("strong");label.className=`tool-result-label${block.result.isError?" error":""}`;label.textContent=block.result.isError?"执行失败":"执行结果";const result=document.createElement("pre");result.className="tool-result";result.textContent=String(block.result.text||"");details.append(label,result)}article.append(details)}}const actions=document.createElement("div");actions.className="actions";if(message.canFork!==false&&message.id)actions.append(action("从这里 fork",()=>forkAt(message.id)));if(message.canEdit&&message.id)actions.append(action("编辑重发",()=>editAndResend(message)));article.append(actions);root.append(article)}for(const result of results){const article=document.createElement("article");article.className="command-result";const title=document.createElement("strong"),pre=document.createElement("pre");title.textContent=`命令结果 · /${result.command}`;pre.textContent=typeof result.output==="string"?result.output:JSON.stringify(result.output,null,2);article.append(title,pre);root.append(article)}root.scrollTop=root.scrollHeight}
async function forkAt(messageId){try{const created=await api(`/sessions/${encodeURIComponent(activeSession)}/fork`,{method:"POST",body:JSON.stringify({messageId})});activeAgent=String(created.agentId||activeAgent);await load();await openSession(String(created.recordId))}catch(error){showError(error,()=>forkAt(messageId))}}
async function editAndResend(message){const original=message.blocks?.filter(block=>block.type==="text").map(block=>block.text).join("\n")||"",replacement=await openEditor({title:"编辑并重发",help:"系统会从这条用户消息之前创建一个新分支，原会话保持不变。",label:"消息内容",value:original,multiline:true,required:true,confirm:"创建分支"});if(replacement===null)return;try{const created=await api(`/sessions/${encodeURIComponent(activeSession)}/messages/${encodeURIComponent(message.id)}/resend`,{method:"POST",body:JSON.stringify({message:replacement})});activeAgent=String(created.agentId||activeAgent);await load();await openSession(String(created.recordId))}catch(error){showError(error,()=>editAndResend(message))}}
async function createSession(){const title=await openEditor({title:"新建会话",help:"会话会创建在当前 Agent 的面板存储中。标题可以留空。",label:"会话标题（可选）",confirm:"创建"});if(title===null)return;try{const created=await api("/sessions",{method:"POST",body:JSON.stringify({agentId:activeAgent,title})});await load();await openSession(String(created.recordId));$("#message").focus()}catch(error){showError(error,createSession)}}
function parseCommand(value){const match=value.trim().match(/^\/([^\s/]+)(?:\s+([\s\S]*))?$/);return match?{command:match[1].toLowerCase(),args:(match[2]?.trim()||"").split(/\s+/).filter(Boolean)}:null}
async function dispatchCommand(value){const parsed=parseCommand(value),catalog=await loadCommands(),known=parsed&&catalog.find(item=>item.name===parsed.command);if(!parsed)throw new Error("命令格式不正确");if(!known?.supported)throw new Error(known?"此命令仅 OpenClaw 原生渠道可用":"面板不支持这个命令");const sourceSession=activeSession,result=await api(`/sessions/${encodeURIComponent(sourceSession)}/command`,{method:"POST",body:JSON.stringify(parsed)});$("#message").value="";hideCommands();if(result?.effect==="created"&&result.data?.recordId){activeAgent=String(result.data.agentId||activeAgent);await load();await openSession(String(result.data.recordId));$("#message").focus();return}if(result?.data!==undefined){const previous=commandResults.get(sourceSession)||[];commandResults.set(sourceSession,[...previous,{command:parsed.command,output:result.data}])}await load();await openSession(sourceSession);$("#message").focus()}
async function search(){const query=$("#search").value.trim();if(!query){renderSessions();return}try{renderSessions(await api(`/search?q=${encodeURIComponent(query)}&agentId=${encodeURIComponent(activeAgent)}`));hideError()}catch(error){showError(error,search)}}
async function consumeEvents(response,onEvent){if(!response.ok){const value=await response.json();throw new Error(value.error?.message||"请求失败")}if(!response.body||!response.headers.get("content-type")?.startsWith("text/event-stream"))throw new Error("服务器未返回事件流");const reader=response.body.getReader(),decoder=new TextDecoder();let buffer="";for(;;){const{done,value}=await reader.read();buffer+=decoder.decode(value||new Uint8Array(),{stream:!done}).replace(/\r\n/g,"\n");let boundary;while((boundary=buffer.indexOf("\n\n"))>=0){const frame=buffer.slice(0,boundary);buffer=buffer.slice(boundary+2);let name="message",data="";for(const line of frame.split("\n")){if(line.startsWith("event:"))name=line.slice(6).trim();else if(line.startsWith("data:"))data+=line.slice(5).trim()}if(data)onEvent(name,JSON.parse(data))}if(done)break}}
$("#search").addEventListener("input",()=>{clearTimeout(searchTimer);searchTimer=setTimeout(search,250)});$("#new-session").onclick=createSession;$("#retry").onclick=()=>retryAction?.();$("#dismiss-error").onclick=hideError;$("#back-agents").onclick=()=>$("#app").className="shell";$("#back-sessions").onclick=()=>$("#app").className="shell show-sessions";$("#logout").onclick=async()=>{try{await api("/auth/logout",{method:"POST",body:"{}"});location.reload()}catch(error){showError(error)}};
$("#message").addEventListener("input",event=>{if(!activeRun)pendingKey=null;event.target.style.height="auto";event.target.style.height=event.target.scrollHeight+"px";void showCommands()});$("#message").addEventListener("keydown",event=>{const menu=$("#command-menu");if(!menu.hidden&&(event.key==="ArrowDown"||event.key==="ArrowUp")){event.preventDefault();moveCommandSelection(event.key==="ArrowDown"?1:-1);return}if(!menu.hidden&&event.key==="Escape"){event.preventDefault();hideCommands();return}if(!menu.hidden&&event.key==="Tab"){const selected=menu.querySelector('[aria-selected="true"]')||menu.querySelector("button:not(:disabled)");if(selected){event.preventDefault();selected.click();return}}if(event.key==="Enter"&&!event.shiftKey){event.preventDefault();$("#composer").requestSubmit()}});$("#message").addEventListener("blur",()=>setTimeout(hideCommands,0));
$("#send").addEventListener("click",event=>{if(activeRun){event.preventDefault();activeRun.abort()}});
$("#composer").addEventListener("submit",event=>{const message=$("#message").value;if(!message.trimStart().startsWith("/"))return;event.preventDefault();event.stopImmediatePropagation();if(!message.trim()||!activeSession||activeRun)return;void dispatchCommand(message).catch(error=>showError(error,()=>$("#composer").requestSubmit()))},{capture:true});
$("#composer").onsubmit=async event=>{event.preventDefault();const textarea=$("#message"),message=textarea.value;if(!message.trim()||!activeSession||activeRun)return;if(message.trimStart().startsWith("/")){showError(new Error("首版暂不支持斜杠命令，请在原有 OpenClaw 渠道执行。"));return}const controller=new AbortController();activeRun=controller;pendingKey=pendingKey||crypto.randomUUID();$("#send").disabled=false;$("#send").textContent="■";$("#send").setAttribute("aria-label","停止生成");try{const response=await fetch(`/api/v1/sessions/${encodeURIComponent(activeSession)}/messages`,{method:"POST",headers:{"content-type":"application/json","x-csrf-token":csrf,"idempotency-key":pendingKey},body:JSON.stringify({message,revision:activeRevision||undefined}),signal:controller.signal});await consumeEvents(response,(name,data)=>{$("#subtitle").textContent=name==="run.started"?"正在生成…":name==="run.completed"?"已完成":name==="run.aborted"?"已取消":"生成失败";if(name==="run.completed"&&data.revision)activeRevision=String(data.revision);if(name==="run.failed")throw new Error(data.message||data.code||"生成失败")});textarea.value="";pendingKey=null;await openSession(activeSession)}catch(error){if(error.name!=="AbortError")showError(error,()=>$("#composer").requestSubmit());else $("#subtitle").textContent="已取消"}finally{activeRun=null;$("#send").textContent="↑";$("#send").setAttribute("aria-label","发送");$("#send").disabled=activeSource!=="panel"}};
setInterval(async()=>{if(document.hidden||!activeAgent||activeRun)return;try{const revisions=await api(`/revisions?agentId=${encodeURIComponent(activeAgent)}`),changed=revisions.some(item=>String(item.revision||"")!==String(sessions.find(session=>String(session.recordId)===String(item.recordId))?.revision||""));if(!changed)return;const active=revisions.find(item=>String(item.recordId)===activeSession),shouldReload=active&&activeRevision&&String(active.revision)!==activeRevision;sessions=await api(`/sessions?agentId=${encodeURIComponent(activeAgent)}`);renderSessions();if(shouldReload)await openSession(activeSession)}catch(error){showError(error,load)}},5000);
boot();
